---
# Gazebo groundtruth
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "ignition.msgs.Clock"
  direction: GZ_TO_ROS
- ros_topic_name: "/spot/joint_states"
  gz_topic_name: "/model/spot/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "ignition.msgs.Model"
  direction: GZ_TO_ROS
- ros_topic_name: "/spot/odometry"
  gz_topic_name: "/model/spot/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "ignition.msgs.Odometry"
  direction: GZ_TO_ROS
# useful for testing
#- ros_topic_name: "/tf"
#  gz_topic_name: "/model/spot/pose"
#  ros_type_name: "tf2_msgs/msg/TFMessage"
#  gz_type_name: "ignition.msgs.Pose_V"
#  direction: GZ_TO_ROS
# Sensors
- ros_topic_name: "/spot/lidar/scan"
  gz_topic_name: "/model/spot/lidar"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "ignition.msgs.LaserScan"
  direction: GZ_TO_ROS
- ros_topic_name: "/spot/lidar/points"
  gz_topic_name: "/model/spot/lidar/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "ignition.msgs.PointCloudPacked"
  direction: GZ_TO_ROS
- ros_topic_name: "/spot/imu"
  gz_topic_name: "/model/spot/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "ignition.msgs.IMU"
  direction: GZ_TO_ROS
- ros_topic_name: "/spot/camera/thermal_camera"
  gz_topic_name: "/model/spot/thermal_camera"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS
- ros_topic_name: "/spot/camera/back_fisheye/image_raw"
  gz_topic_name: "/model/spot/camera/back_fisheye_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS
- ros_topic_name: "/spot/camera/back_fisheye/camera_info"
  gz_topic_name: "/model/spot/camera/back_fisheye_image/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: GZ_TO_ROS
- ros_topic_name: "/spot/camera/frontleft_fisheye/image_raw"
  gz_topic_name: "/model/spot/camera/frontleft_fisheye_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS
- ros_topic_name: "/spot/camera/frontleft_fisheye/camera_info"
  gz_topic_name: "/model/spot/camera/frontleft_fisheye_image/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: GZ_TO_ROS
- ros_topic_name: "/spot/camera/frontright_fisheye/image_raw"
  gz_topic_name: "/model/spot/camera/frontright_fisheye_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "ignition.msgs.Image"
  direction: GZ_TO_ROS
- ros_topic_name: "/spot/camera/frontright_fisheye/camera_info"
  gz_topic_name: "/model/spot/camera/frontright_fisheye_image/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "ignition.msgs.CameraInfo"
  direction: GZ_TO_ROS
# Controller
- ros_topic_name: "/spot/joint_trajectory"
  gz_topic_name: "/model/spot/joint_trajectory"
  ros_type_name: "trajectory_msgs/msg/JointTrajectory"
  gz_type_name: "ignition.msgs.JointTrajectory"
  direction: ROS_TO_GZ
