/**:
  ros__parameters:
      # version
      dlo/version: 1.5.0

      # frames
      dlo/odomNode/odom_frame: "odom_lidar"
      dlo/odomNode/child_frame: "base_link"

      # gravity alignment
      dlo/gravityAlign: false

      # the maximum distance or rotation for generating another key frame
      dlo/odomNode/keyframe/threshD: 1.0
      dlo/odomNode/keyframe/threshR: 45.0

      # submap
      dlo/odomNode/submap/keyframe/knn: 10
      dlo/odomNode/submap/keyframe/kcv: 10
      dlo/odomNode/submap/keyframe/kcc: 10

      # initial position
      dlo/odomNode/initialPose/use: true

      dlo/odomNode/initialPose/position/x: 0.0
      dlo/odomNode/initialPose/position/y: 0.0
      dlo/odomNode/initialPose/position/z: 0.0
      dlo/odomNode/initialPose/orientation/w: 1.0
      dlo/odomNode/initialPose/orientation/x: 0.0
      dlo/odomNode/initialPose/orientation/y: 0.0
      dlo/odomNode/initialPose/orientation/z: 0.0

      # remove points that hit the body of the robot
      dlo/odomNode/preprocessing/cropBoxFilter/use: true
      dlo/odomNode/preprocessing/cropBoxFilter/size: 1.0

      # Voxel filters
      dlo/odomNode/preprocessing/voxelFilter/scan/use: true
      dlo/odomNode/preprocessing/voxelFilter/scan/res: 0.1
      dlo/odomNode/preprocessing/voxelFilter/submap/use: true
      dlo/odomNode/preprocessing/voxelFilter/submap/res: 0.1

      dlo/adaptiveParams: true

      dlo/imu: true
      dlo/odomNode/imu/calibTime: 3
      dlo/odomNode/imu/bufferSize: 2000

      # ICP parameters
      dlo/odomNode/gicp/minNumPoints: 10

      dlo/odomNode/gicp/s2s/kCorrespondences: 80
      dlo/odomNode/gicp/s2s/maxCorrespondenceDistance: 0.05
      dlo/odomNode/gicp/s2s/maxIterations: 32
      dlo/odomNode/gicp/s2s/transformationEpsilon: 0.005
      dlo/odomNode/gicp/s2s/euclideanFitnessEpsilon: 0.01
      dlo/odomNode/gicp/s2s/ransac/iterations: 5
      dlo/odomNode/gicp/s2s/ransac/outlierRejectionThresh: 0.2

      dlo/odomNode/gicp/s2m/kCorrespondences: 80
      dlo/odomNode/gicp/s2m/maxCorrespondenceDistance: 0.05
      dlo/odomNode/gicp/s2m/maxIterations: 32
      dlo/odomNode/gicp/s2m/transformationEpsilon: 0.005
      dlo/odomNode/gicp/s2m/euclideanFitnessEpsilon: 0.01
      dlo/odomNode/gicp/s2m/ransac/iterations: 5
      dlo/odomNode/gicp/s2m/ransac/outlierRejectionThresh: 0.2
