/**:
  ros__parameters:
      # localization node
      dlo/localizationNode/initial_pose_use: true
      dlo/localizationNode/initial_position/x: 0.0
      dlo/localizationNode/initial_position/y: 0.0
      dlo/localizationNode/initial_position/z: 0.0
      dlo/localizationNode/initial_orientation/w: 1.0
      dlo/localizationNode/initial_orientation/x: 0.0
      dlo/localizationNode/initial_orientation/y: 0.0
      dlo/localizationNode/initial_orientation/z: 0.0
